spring:
  # run application mode
  profiles:
    active: ${APP_ENV:test}

  # jpa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # enable snack_case for response JSON
  jackson:
    property-naming-strategy: SNAKE_CASE

# server config
server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api

# spring doc
springdoc:
  api-docs:
    enabled: ${APP_DOCS:true}
    path: /${APP_DOCS_PATH:docs}
  swagger-ui:
    version: 3