spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
